# A collection of functions to visualize the APOGEE and Kepler data
import matplotlib.pyplot as plt

'''
Plots spectras
Inputs:
	spectras - [[Float]], List of spectras of a star to plot
	labels - [String], List of labels for the spectra, otherwise it is generated by default
'''
def plot_spectras(spectras = [], labels = []):
	legends = []
	for i in range(0, len(spectras)):
		# Generate default label
		current_label = "Spectra {}".format(i + 1)
		if i < len(labels):
			current_label = labels[i]
		legends.append(current_label)

		plt.plot(spectras[i], linewidth = 1, alpha = 0.8 - (0.4)/float(len(spectras))*i, label = current_label)
		plt.draw()

	plt.legend(legends)

	plt.xlabel("Wavelength")
	plt.ylabel("Intensity")
	plt.show()